# Generated by Django 3.1.6 on 2021-06-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProsPyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organismo',
            name='aw',
            field=models.FloatField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
